version: "3"
services:
  app:
    restart: always
    build: . # Current directory!
    command: "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - NAME_BD=tesdb
      - USER_BD=cpicos
      - PASSWORD_BD=root
      - HOST_BD=172.16.1.221
      - FILE_SETTINGS=dev_docker
